[package]
name = "cmsisdsp-sys"
version = "1.14.3"
edition = "2021"
authors = ["Sander Wittwer <sander.wittwer@grindoy.no"]

[dependencies]
libm = { version="0.2", optional=true }

[build-dependencies]
cmake = "0.1"
bindgen = "0.64"
regex = "1"

[features]
default = ["ffi"]

ffi = ["libm"]

cortex-m33 = []
intrinsics = []
