[package]
name = "cmsisdsp-sys"
version = "0.1.0"
edition = "2021"
authors = ["Sander Wittwer <sander.wittwer@grindoy.no"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libm = { version="0.2", optional=true }

[build-dependencies]
cmake = "0.1"
bindgen = "0.63"
regex = "1"

[features]
default = ["ffi"]

ffi = ["libm"]

cortex-m33 = []

[profile.dev]
opt-level = 1
debug = true
lto = 'thick'

[profile.release]
opt-level = 3
debug = true
lto = 'thick'
