[package]
name = "cmsisdsp-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
micromath = { version="2", optional=true }

[build-dependencies]
bindgen = "0.63"
regex = "1"

[features]
default = ["vfp"]

vfp = ["micromath"]
