[package]
name = "cmsisdsp-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
zip = { version = "0.6", default-features = false, features = ["deflate"] }
bindgen = "0.63"
reqwest = { version = "0.11.3", default-features = false, features = ["blocking", "default-tls"] }
