name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-x86:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: cargo test --verbose

  build-m33-dsp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.2.Rel1'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: thumbv8m.main-none-eabihf
          override: true
      - name: Build for Cortex M33-DSP
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args:  --target thumbv8m.main-none-eabihf --features ffi,cortex-m33-dsp,intrinsics
